#!/bin/bash
#--------------------------------------
# Script Name:  __PACKAGE_NAME__-docker
# Version:      1.0
# Authors:      skurka@ukaachen.de, akombeiz@ukaachen.de
# Date:         07 Apr 26
# Purpose:      Placeholder service script for Docker-based update execution
#--------------------------------------

set -euo pipefail

# Ensure update directory exists
mkdir -p "__AKTIN_DOCKER_UPDATE_DIR__"

client_ip="${REMOTE_ADDR:-}"
client_port="${REMOTE_PORT:-}"

# Get compose prefix
dwh_prefix="$(
  docker ps -q | while read -r cid; do
    docker inspect \
    --format '{{.Id}} {{range .NetworkSettings.Networks}}{{.IPAddress}} {{end}} {{index .Config.Labels "com.docker.compose.project"}}' \
    "$cid"
  done | awk -v ip="$client_ip" '$0 ~ ip {print $NF; exit}'
)"

# ensure update dir
update_dir="/var/lib/docker/volumes/${dwh_prefix}_aktin_data/_data/update"
mkdir -p "$update_dir"

# find location of compose file
compose_dir="$(docker inspect $dwh_prefix-wildfly-1 --format='{{index .Config.Labels "com.docker.compose.project.config_files"}}')"

# Execute update
cd "$(directory $compose_dir)"
sudo docker compose down
curl -LO https://github.com/aktin/docker-aktin-dwh/releases/latest/download/compose.yml
sudo docker compose pull
sudo docker compose up -d
sudo docker image prune

# Placeholder for future Docker update execution logic
cat <<EOF >"$update_dir/docker-result"
update.success=false
update.time=$(date)
update.message=not_implemented
request.client_ip=${client_ip}
request.client_port=${client_port}
EOF
