#!/bin/bash
#--------------------------------------
# Script Name:  __PACKAGE_NAME__
# Version:      1.0
# Authors:      skurka@ukaachen.de, akombeiz@ukaachen.de
# Date:         14 Nov 24
# Purpose:      Service script to handle DWH package updates
#--------------------------------------

set -euo pipefail

# Ensure update directory exists
mkdir -p "__AKTIN_UPDATE_DIR__"

# Perform update and capture result
if ! { apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install "__DWH_PACKAGE_NAME__" > "__AKTIN_UPDATE_DIR__/log" 2>&1 || echo E: update failed; } | grep -q '^[WE]:'; then
  success="true"
else
  success="false"
fi

# Write result
cat <<EOF >"__AKTIN_UPDATE_DIR__/result"
update.success=${success}
update.time=$(date)
EOF
