#!/bin/bash
#--------------------------------------
# Script Name:  __PACKAGE_NAME__-docker-info
# Version:      1.0
# Authors:      skurka@ukaachen.de, akombeiz@ukaachen.de
# Date:         07 Apr 26
# Purpose:      Placeholder service script for Docker-based update information
#--------------------------------------

set -euo pipefail

client_ip="${REMOTE_ADDR:-}"
client_port="${REMOTE_PORT:-}"
#source summary_aktin-updateagent_preinstall.txt

# read TCP message or leave empty if none
compose_dir=""
dwh_prefix=""
update_dir=""

dwh_prefix="$(
  docker ps -q | while read -r cid; do
    docker inspect --format '{{.id}}} {{rande .NetworkSettings.Networks}}{{.IPAddress}} {{end}} {{index .Config.Labels "com.docker.compose.project"}}' \
    "$cid"
  done | awk -v ip="$client_ip" '$0 ~ ip {print $NF; exit}'
)"

echo "debug: value=$dwh_prefix" >&2
update_dir="/var/lib/docker/volumes/${dwh_prefix}_aktin_data/_data/update"
mkdir -p "$update_dir"

cat <<EOF > "$update_dir/info"
version.installed=
version.candidate=
version.time=$(date)
request.client_ip=${client_ip}
request.client_port=${client_port}
request.client_prefix=${dwh_prefix}
EOF


#
#echo "$date" >> "__AKTIN_DOCKER_UPDATE_DIR__/info.txt"
#echo "$client_ip" >> "__AKTIN_DOCKER_UPDATE_DIR__/info.txt"
#echo "$client_port" >> "__AKTIN_DOCKER_UPDATE_DIR__/info.txt"

#if IFS= read -r -t 2 -N 1024 compose_dir; then
#    compose_dir="$(printf '%s' "$compose_dir" | tr -d '\000-\010\013\014\016-\037\177' | tr '\r\n' '  ')"
#    dwh_prefix="$(basename $compose_dir)"
#    update_dir=$(find -type d -name $dwh_prefix"_aktin_data") "/_data/update"
#else
#    exit 1  # no tcp-message received
#fi

# Placeholder for future Docker update info logic
#cat <<EOF > "__AKTIN_DOCKER_UPDATE_DIR__/info.txt"
#version.installed=
#version.candidate=
#version.time=$(date)
#version.message=not_implemented
#request.client_ip=${client_ip}
#request.client_port=${client_port}
#dir=${$update_dir}
#EOF
