#!/bin/bash
#--------------------------------------
# Script Name:  preinst
# Version:      1.0
# Authors:      whoy@ukaachen.de
# Date:         10 Apr 26
# Purpose:      Checks target system for requirements. Cancel installation if environment is insufficient
#--------------------------------------

readonly PACKAGE_NAME="__PACKAGE_NAME__"

log_info() { echo -e "\033[0;34m[INFO]\033[0m $1"; logger -t "${PACKAGE_NAME}" -p user.info -- "$1" 2>/dev/null || true; }
log_success() { echo -e "\033[0;32m[SUCCESS]\033[0m $1"; logger -t "${PACKAGE_NAME}" -p user.notice -- "$1" 2>/dev/null || true; }
log_warn() { echo -e "\033[1;33m[WARN]\033[0m $1"; logger -t "${PACKAGE_NAME}" -p user.warning -- "$1" 2>/dev/null || true; }
log_error() { echo -e "\033[0;31m[ERROR]\033[0m $1" >&2; logger -t "${PACKAGE_NAME}" -p user.err -- "$1" 2>/dev/null || true; }

readonly OPERATION="${1}"
readonly UPDATE_DIR="/var/lib/aktin/update"
readonly DEBIAN_SERVICE="wildfly.service"

# Requirement: Any kind of dwh has to be installed
is_installed_debian() {
  if systemctl list-unit-files | grep -q "wildfly"; then
      log_info "WildFly service is installed"
      return 0
  else
      log_info "WildFly service is NOT installed"
      return 1
  fi
}

is_installed_docker() {
  command -v docker >/dev/null 2>&1 || return 1   # return 1 if docker is not in PATH

  # check repositories of installed images
  local required="
ghcr.io/aktin/notaufnahme-dwh-wildfly
ghcr.io/aktin/notaufnahme-dwh-httpd
ghcr.io/aktin/notaufnahme-dwh-database
"
  local installed=$(docker images --format "{{.Repository}}")
  for img in $required; do
    if ! echo "$installed" | grep -qx "$img"; then
      return 1  # return 1 if any required image-repository does not exist
    fi
  done
  return 0
}


main() {
  set -euo pipefail
  case "$OPERATION" in
    install)
      # Runs during package installation before unpacking archive.
      set +e
      is_installed_debian
      debian_status=$?
      is_installed_docker
      docker_status=$?
      set -e

      log_info "debian dwh status: $debian_status"
      log_info "docker dwh status: $docker_status"

      cat <<EOF > "/tmp/summary_aktin-updateagent_preinstall.txt"
debian_installed=$debian_status
docker_installed=$docker_status
EOF
      ;;
    upgrade)
      # Runs during package upgrade before unpacking new archive.
      ;;
  esac
}

main "$@"
