name: docker-integration-test.yml
run-name: Testing changes from user ${{ github.actor }}
on: [ push ]

env:
  PORT: 8080
  API: localhost:8080/aktin/admin/rest
  COMPOSE: https://github.com/aktin/docker-aktin-dwh/releases/download/v1.6rc1-3-db01-wf01-httpd01/compose.yml

jobs:
  updateagent-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build updateagent package
        run: |
          chmod +x ./src/debian/build.sh
          ./src/debian/build.sh --cleanup

      - name: Find debian file
        run: |
          DEB_PATH=$(find . -type f -name "*.deb" | head -n 1)
          echo "DEB_PATH=$DEB_PATH" >> "$GITHUB_ENV"
          echo "Found debian package: $DEB_PATH"

      - name: Upload debian file
        uses: actions/upload-artifact@v4
        with:
          name: deb-file
          path: ${{ env.DEB_PATH }}

  updateagent-test:
    needs: updateagent-build
    runs-on: ubuntu-22.04
    steps:
      - name: Install Docker
        run: |
          sudo apt update
          sudo apt install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          
          sudo tee /etc/apt/sources.list.d/docker.sources <<EOF
          Types: deb
          URIs: https://download.docker.com/linux/ubuntu
          Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
          Components: stable
          Architectures: $(dpkg --print-architecture)
          Signed-By: /etc/apt/keyrings/docker.asc
          EOF
          sudo apt update
          sudo apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Install DWH (Docker, old release)
        run: |
          mkdir -p /opt/docker-deploy/aktin-dwh/dwh1
          chown -R $USER:$USER /opt/docker-deploy/aktin-dwh/
          chmod 750 /opt/docker-deploy/aktin-dwh/dwh1
          cd /opt/docker-deploy/aktin-dwh/dwh1
          curl -LO $COMPOSE
          openssl rand -base64 32 > secret.txt
          echo "HTTP_PORT=${{ env.PORT }}" > .env
          docker compose up -d

      - name: Verify Docker DWH
        run: |
          echo "$(sudo docker ps)"
          sleep 10s
          TOKEN=$(curl -s -X POST "${{ env.API }}"/auth/login -H 'Content-Type: application/json' -d '{"username":"${{ secrets.USERNAME }}","password":"${{ secrets.PASSWORD }}"}')
          echo "Got token: $TOKEN"
          echo "TOKEN=$TOKEN" >> "$GITHUB_ENV"
          echo $(curl -H "Authorization: Bearer ${{ env.TOKEN }}" "${{ env.API }}/auth/check")


      - name: Load already-built debian package
        uses: actions/download-artifact@v4
        with:
          name: deb-file

      - name: Find debian file
        run: |
          DEB_PATH_VM=$(find . -type f -name "*.deb" | head -n 1)
          echo "DEB_PATH_VM=$DEB_PATH_VM" >> "$GITHUB_ENV"
          echo "Found debian package: $DEB_PATH_VM"
          echo "DEB_NAME=$(basename $DEB_PATH_VM)" >> "$GITHUB_ENV"

      - name: Install required packages for debian file
        run: |
          sudo apt install unattended-upgrades

      - name: Install debian package
        run: |
          sudo dpkg -i "$DEB_PATH_VM"

      - name: Verify installation
        run: |
          sudo apt-cache policy "$DEB_NAME"

      - name: Update DWH
        run: |
          curl -X POST -H "Authorization: Bearer ${{ env.TOKEN }}" "${{ env.API }}/update"
          

