name: docker-integration-test.yml
run-name: Testing changes from user ${{ github.actor }}
on: [push]

jobs:
  updateagent-install:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show files
        run: |
          pwd
          ls -lah
          
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential debhelper devscripts

      - name: Build updateagent package
        run: |
          chmod +x ./src/debian/build.sh
          ./src/debian/build.sh --cleanup

      - name: Install updateagent package
        run: |
          DEB_NAME=$(find -type f -name "*.deb")
          echo "$DEB_NAME"
          sudo dpkg -i "src/build/$DEB_NAME"

      - name: Verify installation
        run: |
          sudo apt-cache policy "$DEB_NAME"
